import { describe, expect, it, vi } from 'vitest'

vi.mock('@/lib/monacoSetup', () => ({ monaco: {} }))

import { isGeneratedGoFile } from './goStudioExtraLanguages'

describe('generated Go files', () => {
  it('recognises the standard generated header only in Go files', () => {
    const header = '// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n'
    expect(isGeneratedGoFile('pb/api.pb.go', header)).toBe(true)
    expect(isGeneratedGoFile('README.md', header)).toBe(false)
    expect(isGeneratedGoFile('main.go', 'package main\n// Code generated but edited by hand\n')).toBe(false)
  })
})
