import type { ComponentType } from 'react'
import {
  Fullscreen, PanelLeft,
  AlignLeft, ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpDown, Binary, Bookmark, BookmarkPlus, BookOpen, Braces, Bug,
  CircleCheck, CircleDot, CircleHelp, CirclePause, CirclePlay, CircleStop, Code2, Columns2, Compass, Copy, Download,
  Eye, EyeOff, FileCode2, FilePlus2, FileSearch, FileText, FlaskConical, FlaskRound, FolderOpen, FolderPlus, FolderX,
  GitBranch, GitCommitHorizontal, GitCompare, GitGraph, GitPullRequestArrow, Hammer, History, Keyboard, Layers, Lightbulb,
  ListChecks, ListTodo, ListTree, Maximize2, MessageSquareCode, MousePointerClick, MoveDown, MoveUp, Network, PackageCheck,
  PackageOpen, PackagePlus, PackageSearch, Paintbrush, PanelBottom, PanelRight, PanelTop, Pencil, Pin, Play, Plug,
  Radar, Redo2, RefreshCw, Send, Repeat, Replace, RotateCcw, Rows2, Save, SaveAll, ScanSearch, Search, SearchCode, Server,
  Settings2, ShieldCheck, Sparkles, Square, SquareDashed, SquareTerminal, StepForward, Terminal, TextCursorInput, Trash2,
  Type, Undo2, Unplug, Wand2, WandSparkles, Workflow, Wrench, X, Zap, type LucideIcon, ArrowUpToLine, Boxes, Eraser, Focus, Ligature, Map, ZoomIn, ZoomOut, PenLine, ShieldAlert, CircleSlash
} from 'lucide-react'
import { GoGopherIcon } from './GoGopherIcon'
import type { GoStudioCommandId, GoStudioMenuId } from './goStudioCommands'

export interface GoStudioCommandIcon {
  icon: ComponentType<{ size?: number; className?: string }>
  /** Colore semantico: verde per eseguire, blu per il debug, rosso per fermare. */
  tone?: string
}

const RUN = 'text-success'
const DEBUG = 'text-info'
const STOP = 'text-danger'
const TEST = 'text-accent'

const icon = (value: LucideIcon, tone?: string): GoStudioCommandIcon => ({ icon: value, tone })

/** Icona di ogni menu principale nel pulsante ☰. */
export const GO_STUDIO_MENU_ICONS: Record<GoStudioMenuId, GoStudioCommandIcon> = {
  file: icon(FileText),
  edit: icon(Pencil),
  view: icon(Eye),
  navigate: icon(Compass),
  code: icon(Code2),
  go: { icon: GoGopherIcon },
  run: icon(Play, RUN),
  tools: icon(Wrench),
  git: icon(GitBranch),
  help: icon(CircleHelp),
}

/** Icona di ogni comando. Un comando senza voce resta allineato con una colonna vuota. */
export const GO_STUDIO_COMMAND_ICONS: Partial<Record<GoStudioCommandId, GoStudioCommandIcon>> = {
  'file.openProject': icon(FolderOpen),
  'file.newProject': icon(FolderPlus),
  'file.save': icon(Save),
  'file.saveAll': icon(SaveAll),
  'file.closeEditor': icon(X),
  'file.closeOthers': icon(SquareDashed),
  'file.closeAll': icon(Trash2),
  'file.pinTab': icon(Pin),
  'file.reopenClosed': icon(RotateCcw),
  'file.localHistory': icon(History),
  'file.closeProject': icon(FolderX),
  'window.openInNewWindow': icon(PanelTop),
  'window.moveBack': icon(ArrowLeft),

  'edit.undo': icon(Undo2),
  'edit.redo': icon(Redo2),
  'edit.find': icon(Search),
  'edit.replace': icon(Replace),
  'edit.gotoLine': icon(ArrowDownToLine),
  'edit.toggleComment': icon(MessageSquareCode),
  'edit.duplicateLine': icon(Copy),
  'edit.deleteLine': icon(Trash2),
  'edit.moveLineUp': icon(MoveUp),
  'edit.moveLineDown': icon(MoveDown),
  'edit.nextOccurrence': icon(TextCursorInput),
  'edit.allOccurrences': icon(MousePointerClick),
  'edit.columnSelection': icon(Columns2),

  'view.quickOpen': icon(FileSearch),
  'view.maximize': icon(Maximize2),
  'file.clone': icon(GitBranch),
  'go.goWork': icon(Boxes),
  'nav.recentLocations': icon(History),
  'nav.lastEdit': icon(PenLine),
  'nav.gotoTest': icon(FlaskConical),
  'code.generate': icon(Sparkles),
  'nav.callHierarchy': icon(Network),
  'nav.typeHierarchy': icon(Boxes),
  'nav.nextProblem': icon(ArrowDownToLine),
  'nav.previousProblem': icon(ArrowUpToLine),
  'view.zoomIn': icon(ZoomIn),
  'view.zoomOut': icon(ZoomOut),
  'view.zoomReset': icon(Search),
  'view.zenMode': icon(Focus),
  'view.stickyScroll': icon(Pin),
  'view.minimap': icon(Map),
  'view.fontLigatures': icon(Ligature),
  'view.previewTab': icon(Eye),
  'code.typeHints': icon(Type),
  'file.autoSave': icon(Save),
  'file.trimWhitespace': icon(Eraser),
  'view.maximizeEditor': icon(Fullscreen),
  'view.toggleProject': icon(PanelLeft),
  'view.toggleStructure': icon(PanelRight),
  'view.toggleBottom': icon(PanelBottom),
  'view.problems': icon(CircleDot),
  'view.terminal': icon(SquareTerminal),
  'view.tests': icon(FlaskConical),
  'view.todo': icon(ListTodo),
  'view.debug': icon(Bug),
  'view.splitRight': icon(Columns2),
  'view.splitDown': icon(Rows2),
  'view.unsplit': icon(Square),
  'view.toggleIgnored': icon(EyeOff),

  'nav.searchEverywhere': icon(Search),
  'nav.declaration': icon(ArrowRight),
  'nav.typeDeclaration': icon(Type),
  'nav.implementation': icon(Layers),
  'nav.superMethod': icon(MoveUp),
  'nav.usages': icon(ScanSearch),
  'nav.showUsages': icon(ListTree),
  'nav.quickDefinition': icon(Eye),
  'nav.fileStructure': icon(Braces),
  'nav.back': icon(ArrowLeft),
  'nav.forward': icon(ArrowRight),
  'nav.toggleBookmark': icon(BookmarkPlus),
  'nav.bookmarks': icon(Bookmark),
  'nav.symbol': icon(Binary),
  'nav.findInFiles': icon(SearchCode),

  'code.completion': icon(Sparkles),
  'code.parameterInfo': icon(Braces),
  'code.quickDocumentation': icon(BookOpen),
  'code.typeInfo': icon(Type),
  'code.quickFix': icon(Lightbulb, 'text-warning'),
  'code.implementInterface': icon(PackagePlus),
  'code.rename': icon(Pencil),
  'code.refactorThis': icon(Wand2),
  'code.extractVariable': icon(FileCode2),
  'code.extractConstant': icon(FileCode2),
  'code.extractFunction': icon(FileCode2),
  'code.inline': icon(ArrowUpDown),
  'code.moveToNewFile': icon(FilePlus2),
  'code.reformat': icon(AlignLeft),
  'code.organizeImports': icon(ListChecks),
  'code.lint': icon(Radar),
  'code.formatOnSave': icon(AlignLeft),
  'code.importsOnSave': icon(ListChecks),
  'code.lintOnSave': icon(Radar),
  'code.semanticHighlighting': icon(Paintbrush),
  'code.inlayHints': icon(Type),
  'code.gofumpt': icon(WandSparkles),
  'code.staticcheck': icon(ShieldCheck),
  'code.vulncheck': icon(ShieldAlert),

  'go.toolchains': icon(Settings2),
  'go.detect': icon(RefreshCw),
  'go.dependencies': icon(PackageSearch),
  'go.tidy': icon(PackageCheck),
  'go.updateAll': icon(ArrowUpDown),
  'go.updatePatch': icon(ArrowUpDown),
  'go.modDownload': icon(Download),
  'go.modVerify': icon(CircleCheck),
  'go.toolVet': icon(ShieldCheck),
  'go.toolGenerate': icon(Workflow),
  'go.toolFix': icon(Wrench),
  'go.toolModWhy': icon(CircleHelp),
  'go.toolModGraph': icon(GitGraph),
  'go.toolDoc': icon(BookOpen),
  'go.trust': icon(ShieldCheck, RUN),
  'go.lspStart': icon(Plug, RUN),
  'go.lspRestart': icon(RefreshCw),
  'go.lspStop': icon(Unplug, STOP),
  'go.lspInstall': icon(Download),
  'go.lspLog': icon(Terminal),
  'go.installGolangci': icon(Download),
  'go.installStaticcheck': icon(Download),
  'go.installDelve': icon(Download),
  'go.toolPaths': icon(Settings2),

  'run.run': icon(Play, RUN),
  'debug.debug': icon(Bug, DEBUG),
  'debug.attach': icon(Network),
  'debug.remote': icon(Server),
  'run.build': icon(Hammer),
  'run.buildPackage': icon(PackageOpen),
  'run.testPackage': icon(FlaskConical, TEST),
  'run.vetPackage': icon(ShieldCheck),
  'run.testCoverage': icon(FlaskRound, TEST),
  'run.testRace': icon(Zap, 'text-warning'),
  'run.runRace': icon(Zap, 'text-warning'),
  'run.rerunFailedTests': icon(Repeat, STOP),
  'run.buildAll': icon(PackageOpen),
  'run.testAll': icon(FlaskConical, TEST),
  'run.vetAll': icon(ShieldCheck),
  'run.generateAll': icon(Workflow),
  'run.install': icon(Download),
  'run.stop': icon(Square, STOP),
  'run.restart': icon(RotateCcw),
  'debug.toggleBreakpoint': icon(CircleDot, STOP),
  'debug.viewBreakpoints': icon(ListChecks),
  'debug.muteBreakpoints': icon(CircleSlash),
  'debug.runToCursor': icon(TextCursorInput, RUN),
  'debug.resume': icon(CirclePlay, RUN),
  'debug.pause': icon(CirclePause),
  'debug.stepOver': icon(StepForward),
  'debug.stepInto': icon(ArrowDownToLine),
  'debug.stepOut': icon(MoveUp),
  'debug.stop': icon(CircleStop, STOP),
  'run.configure': icon(Settings2),

  'tools.services': icon(Server),
  'tools.httpRequest': icon(Send),
  'tools.plugins': icon(Plug),

  'vcs.commit': icon(GitCommitHorizontal),
  'vcs.history': icon(History),
  'vcs.annotate': icon(GitCompare),
  'vcs.gitStudio': icon(GitPullRequestArrow),

  'help.shortcuts': icon(Keyboard),
}
