// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bootstrap$0 from "./internal/bootstrap/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as markdown$0 from "./internal/markdown/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachDesktop gives the binding service access to the Wails v3 application.
 * Domain code remains independent from Wails; only this root binding layer
 * touches native windows, dialogs, and the application event bus.
 */
export function AttachDesktop(desktop: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1686756476, desktop);
}

export function AttachRequestToMainWindow(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(3934585569, tabID);
}

export function BuildPSD2Headers(inputJSON: string): $CancellablePromise<string> {
    return $Call.ByID(2888181038, inputJSON);
}

/**
 * CancelHTTP aborts an in-flight ExecuteHTTP request by its frontend id.
 */
export function CancelHTTP(id: string): $CancellablePromise<void> {
    return $Call.ByID(716153779, id);
}

/**
 * CheckForUpdate queries the latest GitHub release after an explicit user action
 * and reports whether a newer version exists. Returns a frontend-safe error on
 * failure.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2347956003).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearDevLogs(): $CancellablePromise<void> {
    return $Call.ByID(2262681050);
}

export function CompareFolders(left: string, right: string, maxFileMB: number): $CancellablePromise<string> {
    return $Call.ByID(3985885649, left, right, maxFileMB);
}

export function CreateMarkdownFile(root: string, relPath: string, content: string): $CancellablePromise<markdown$0.FileEntry> {
    return $Call.ByID(3160060858, root, relPath, content).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteMarkdownFile(root: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(3359850697, root, relPath);
}

/**
 * DetachRequest creates a native Wails v3 window for the existing request tab.
 * snapshotJSON contains the request, response and editor view state; it is kept
 * in the single app process until the request is attached again.
 */
export function DetachRequest(tabID: string, snapshotJSON: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(346379527, tabID, snapshotJSON, title);
}

/**
 * DetachRequestAndResponse opens the composer and response in two native
 * windows while keeping a single synchronized request tab session.
 */
export function DetachRequestAndResponse(tabID: string, snapshotJSON: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2949879727, tabID, snapshotJSON, title);
}

/**
 * ExecuteHTTP preserves the public Wails binding while execution lives in the HTTP module.
 */
export function ExecuteHTTP(reqJSON: string): $CancellablePromise<string> {
    return $Call.ByID(3390070976, reqJSON);
}

/**
 * GetAppVersion returns the embedded build version (or "dev").
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1780012486);
}

export function GetDetachedRequestSnapshot(tabID: string): $CancellablePromise<string> {
    return $Call.ByID(1276708202, tabID);
}

export function GetDevLogs(): $CancellablePromise<string> {
    return $Call.ByID(471003717);
}

export function GetServerPort(): $CancellablePromise<number> {
    return $Call.ByID(1323345775);
}

export function GetSidecarToken(): $CancellablePromise<string> {
    return $Call.ByID(707932735);
}

export function GetStartupWindowChrome(): $CancellablePromise<string> {
    return $Call.ByID(2761809102);
}

/**
 * GetVaultTimeout returns the vault auto-lock timeout in minutes.
 */
export function GetVaultTimeout(): $CancellablePromise<number> {
    return $Call.ByID(2622322516);
}

export function ImportMarkdownFolderToWorkspace(sourceRoot: string): $CancellablePromise<markdown$0.WorkspaceInfo> {
    return $Call.ByID(421526873, sourceRoot).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InspectPSD2Certificate(path: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(4289025119, path, password);
}

export function InspectSigningCertificateBase64(reqJSON: string): $CancellablePromise<string> {
    return $Call.ByID(3125294382, reqJSON);
}

/**
 * IsDevMode returns whether developer mode is enabled.
 */
export function IsDevMode(): $CancellablePromise<boolean> {
    return $Call.ByID(1362385015);
}

/**
 * ListLogFiles returns the list of JSONL log files in the logs directory.
 */
export function ListLogFiles(): $CancellablePromise<$models.LogFileEntry[]> {
    return $Call.ByID(2963318464).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListMarkdownFiles(root: string): $CancellablePromise<markdown$0.FileEntry[]> {
    return $Call.ByID(2340622615, root).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadBootstrapState keeps the Wails binding thin while the internal package
 * performs one transaction for all state required by the first workspace.
 */
export function LoadBootstrapState(): $CancellablePromise<bootstrap$0.State> {
    return $Call.ByID(705221870).then(($result: any) => {
        return $$createType6($result);
    });
}

export function LoadBootstrapStateV2(): $CancellablePromise<bootstrap$0.StateV2> {
    return $Call.ByID(1584322926).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * LoadCollectionWorkspace hydrates one non-active workspace on first access.
 */
export function LoadCollectionWorkspace(workspaceID: string): $CancellablePromise<string> {
    return $Call.ByID(245840982, workspaceID);
}

export function LoadSettings(): $CancellablePromise<string> {
    return $Call.ByID(3551729052);
}

export function OnApplicationShutdown(): $CancellablePromise<void> {
    return $Call.ByID(4168079000);
}

export function OnDomReady(): $CancellablePromise<void> {
    return $Call.ByID(3093038483);
}

export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(999779538);
}

export function OnStartup(): $CancellablePromise<void> {
    return $Call.ByID(2232168041);
}

/**
 * OpenDevLogsFolder opens the dev logs directory in the OS file manager.
 */
export function OpenDevLogsFolder(): $CancellablePromise<void> {
    return $Call.ByID(410991487);
}

/**
 * OpenSwaggerEditorWindow opens the OpenAPI editor in its own native window.
 * The editor remains local-first: its draft is persisted by the frontend in
 * local storage and can be saved into any local collection from that window.
 */
export function OpenSwaggerEditorWindow(): $CancellablePromise<void> {
    return $Call.ByID(976830226);
}

export function ReadDroppedFiles(paths: string[]): $CancellablePromise<string> {
    return $Call.ByID(1904195336, paths);
}

export function ReadFolderDiffFile(scanID: string, path: string, maxBytes: number): $CancellablePromise<string> {
    return $Call.ByID(3935767324, scanID, path, maxBytes);
}

/**
 * ReadLogFile reads a JSONL log file and returns its entries as a JSON array.
 */
export function ReadLogFile(filename: string): $CancellablePromise<string> {
    return $Call.ByID(1213777519, filename);
}

export function ReadMarkdownFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2283889154, path);
}

export function RecordFrontendLog(level: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3326668850, level, message);
}

/**
 * RecordStartupPerformance appends one timing-only sample after the renderer's
 * first stable frame. The internal recorder is local-only and independent from
 * Dev Log cleanup, so medians can be calculated across process launches.
 */
export function RecordStartupPerformance(frontendJSON: string): $CancellablePromise<void> {
    return $Call.ByID(1831790581, frontendJSON);
}

export function RenameMarkdownFile(root: string, oldRelPath: string, newRelPath: string): $CancellablePromise<markdown$0.FileEntry> {
    return $Call.ByID(3235207952, root, oldRelPath, newRelPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveBinaryFileBase64(defaultName: string, dataBase64: string): $CancellablePromise<string> {
    return $Call.ByID(2819397220, defaultName, dataBase64);
}

/**
 * SaveCollectionWorkspaces atomically updates the v3 shards and the complete
 * v2 compatibility snapshot outside the startup critical path.
 */
export function SaveCollectionWorkspaces(indexJSON: string, workspaceJSON: string[]): $CancellablePromise<void> {
    return $Call.ByID(710926, indexJSON, workspaceJSON);
}

export function SaveMarkdownFileAs(defaultName: string, content: string): $CancellablePromise<markdown$0.FileEntry> {
    return $Call.ByID(305697395, defaultName, content).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveSettings(settingsJSON: string): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settingsJSON);
}

export function SelectExtensionArchive(): $CancellablePromise<string> {
    return $Call.ByID(2224333856);
}

export function SelectFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(237181597, title);
}

/**
 * SelectPSD2Certificate opens a native picker and returns a local path only.
 */
export function SelectPSD2Certificate(): $CancellablePromise<string> {
    return $Call.ByID(1966586193);
}

/**
 * SetDevMode enables or disables developer mode.
 */
export function SetDevMode(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3377656721, enabled);
}

export function SetMainWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(843697430, window);
}

/**
 * SetVaultTimeout sets the vault auto-lock timeout in minutes.
 */
export function SetVaultTimeout(minutes: number): $CancellablePromise<void> {
    return $Call.ByID(145647744, minutes);
}

export function SignPdfDocumentBase64(reqJSON: string): $CancellablePromise<string> {
    return $Call.ByID(2625311448, reqJSON);
}

export function StorageDelete(bucket: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(3271435961, bucket, key);
}

export function StorageGet(bucket: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1545378586, bucket, key);
}

export function StorageGetAll(bucket: string): $CancellablePromise<$models.StorageEntry[]> {
    return $Call.ByID(2257741921, bucket).then(($result: any) => {
        return $$createType9($result);
    });
}

export function StorageList(bucket: string, prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(3840110650, bucket, prefix).then(($result: any) => {
        return $$createType10($result);
    });
}

export function StoragePut(bucket: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1223057291, bucket, key, value);
}

export function UpdateDetachedRequestSnapshot(tabID: string, snapshotJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3907882895, tabID, snapshotJSON);
}

export function VerifyPdfSignatureBase64(pdfBase64: string): $CancellablePromise<string> {
    return $Call.ByID(337391375, pdfBase64);
}

export function WriteMarkdownAgentGraph(root: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3325475990, root, content);
}

export function WriteMarkdownFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1075399659, path, content);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = markdown$0.FileEntry.createFrom;
const $$createType2 = markdown$0.WorkspaceInfo.createFrom;
const $$createType3 = $models.LogFileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = bootstrap$0.State.createFrom;
const $$createType7 = bootstrap$0.StateV2.createFrom;
const $$createType8 = $models.StorageEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
