// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DevContext exposes the project context of gO sessions to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devcontext$0 from "./internal/devcontext/models.js";

/**
 * CheckStale rescans files changed outside gO; true when something changed.
 */
export function CheckStale(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2169833367, sessionID);
}

/**
 * GetContext returns the context of a gO session, scanning it on first use.
 */
export function GetContext(sessionID: string): $CancellablePromise<devcontext$0.Snapshot> {
    return $Call.ByID(276047489, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReadContextFile returns an OpenAPI, proto or WSDL document of the session.
 */
export function ReadContextFile(sessionID: string, relPath: string): $CancellablePromise<string> {
    return $Call.ByID(1346169035, sessionID, relPath);
}

/**
 * RescanContext forces a full rescan of the session folder.
 */
export function RescanContext(sessionID: string): $CancellablePromise<devcontext$0.Snapshot> {
    return $Call.ByID(1975717609, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = devcontext$0.Snapshot.createFrom;
