// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtensionService is the intentionally small Wails binding layer for
 * Extension Platform v2. Host lifecycle and HTTP transform methods remain
 * private; the renderer can emit only the bounded, allowlisted workbench events
 * whose canonical stores live in the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extensions$0 from "./internal/extensions/models.js";

export function Contributions(): $CancellablePromise<extensions$0.Manifest[]> {
    return $Call.ByID(488422155).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Disable(id: string): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(1711978116, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Enable(id: string): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(3236311127, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ExecuteCommand(extensionID: string, commandID: string, argsJSON: string, source: string): $CancellablePromise<extensions$0.HostExecutionResult> {
    return $Call.ByID(1904810740, extensionID, commandID, argsJSON, source).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExportSDK(destination: string): $CancellablePromise<string> {
    return $Call.ByID(552441318, destination);
}

export function GetDiagnostics(extensionID: string): $CancellablePromise<extensions$0.ExtensionDiagnostic[]> {
    return $Call.ByID(2200303080, extensionID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetExtensions(): $CancellablePromise<extensions$0.ExtensionInstance[]> {
    return $Call.ByID(2859212398).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetLogs(extensionID: string): $CancellablePromise<extensions$0.ExtensionLog[]> {
    return $Call.ByID(905320927, extensionID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetRuntimeStatus(): $CancellablePromise<extensions$0.RuntimeStatus> {
    return $Call.ByID(1574664858).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetViewState(extensionID: string, viewID: string): $CancellablePromise<string> {
    return $Call.ByID(527321214, extensionID, viewID);
}

export function GetWebviewHTML(extensionID: string, viewID: string): $CancellablePromise<string> {
    return $Call.ByID(1075799222, extensionID, viewID);
}

export function InstallArchive(path: string): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(1538799283, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InstallDirectory(path: string, development: boolean): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(403846698, path, development).then(($result: any) => {
        return $$createType2($result);
    });
}

export function NotifyWorkbenchEvent(event: string, payloadJSON: string): $CancellablePromise<void> {
    return $Call.ByID(2623827790, event, payloadJSON);
}

export function OpenView(extensionID: string, viewID: string): $CancellablePromise<string> {
    return $Call.ByID(4041146097, extensionID, viewID);
}

export function Reload(id: string): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(653230909, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetDomainContext(contextJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3430194087, contextJSON);
}

export function SetGrants(id: string, grants: string[]): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(717134199, id, grants).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetSetting(id: string, key: string, valueJSON: string): $CancellablePromise<extensions$0.ExtensionInstance> {
    return $Call.ByID(1744082356, id, key, valueJSON).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetWorkspaceContext(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(701699196, workspaceID);
}

export function Uninstall(id: string): $CancellablePromise<void> {
    return $Call.ByID(196426714, id);
}

// Private type creation functions
const $$createType0 = extensions$0.Manifest.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = extensions$0.ExtensionInstance.createFrom;
const $$createType3 = extensions$0.HostExecutionResult.createFrom;
const $$createType4 = extensions$0.ExtensionDiagnostic.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = extensions$0.ExtensionLog.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = extensions$0.RuntimeStatus.createFrom;
