// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommitResult {
    "hash": string;
    "message": string;

    /** Creates a new CommitResult instance. */
    constructor($$source: Partial<CommitResult> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitResult($$parsedSource as Partial<CommitResult>);
    }
}

/**
 * PullRequest is the trimmed PR shape the UI needs.
 */
export class PullRequest {
    "number": number;
    "title": string;
    "state": string;
    "author": string;
    "head": string;
    "base": string;
    "url": string;
    "draft": boolean;

    /** Creates a new PullRequest instance. */
    constructor($$source: Partial<PullRequest> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("head" in $$source)) {
            this["head"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("draft" in $$source)) {
            this["draft"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PullRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PullRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PullRequest($$parsedSource as Partial<PullRequest>);
    }
}
