// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandContribution {
    "id": string;
    "title": string;
    "category"?: string;
    "icon"?: string;

    /** Creates a new CommandContribution instance. */
    constructor($$source: Partial<CommandContribution> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandContribution instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandContribution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandContribution($$parsedSource as Partial<CommandContribution>);
    }
}

export class ConfigurationProperty {
    "type": string;
    "default"?: any;
    "description"?: string;
    "enum"?: any[];
    "minimum"?: number | null;
    "maximum"?: number | null;

    /** Creates a new ConfigurationProperty instance. */
    constructor($$source: Partial<ConfigurationProperty> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigurationProperty instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigurationProperty {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enum" in $$parsedSource) {
            $$parsedSource["enum"] = $$createField3_0($$parsedSource["enum"]);
        }
        return new ConfigurationProperty($$parsedSource as Partial<ConfigurationProperty>);
    }
}

export class Contributions {
    "commands"?: CommandContribution[];
    "views"?: ViewContribution[];
    "configuration"?: { [_ in string]?: ConfigurationProperty };
    "keybindings"?: KeybindingContribution[];
    "menus"?: { [_ in string]?: MenuContribution[] };
    "statusBar"?: StatusBarContribution[];

    /** Creates a new Contributions instance. */
    constructor($$source: Partial<Contributions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Contributions instance from a string or object.
     */
    static createFrom($$source: any = {}): Contributions {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField0_0($$parsedSource["commands"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField1_0($$parsedSource["views"]);
        }
        if ("configuration" in $$parsedSource) {
            $$parsedSource["configuration"] = $$createField2_0($$parsedSource["configuration"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField3_0($$parsedSource["keybindings"]);
        }
        if ("menus" in $$parsedSource) {
            $$parsedSource["menus"] = $$createField4_0($$parsedSource["menus"]);
        }
        if ("statusBar" in $$parsedSource) {
            $$parsedSource["statusBar"] = $$createField5_0($$parsedSource["statusBar"]);
        }
        return new Contributions($$parsedSource as Partial<Contributions>);
    }
}

export class Engines {
    "adomnia": string;

    /** Creates a new Engines instance. */
    constructor($$source: Partial<Engines> = {}) {
        if (!("adomnia" in $$source)) {
            this["adomnia"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Engines instance from a string or object.
     */
    static createFrom($$source: any = {}): Engines {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Engines($$parsedSource as Partial<Engines>);
    }
}

export class ExtensionDiagnostic {
    "extensionId": string;
    "severity": string;
    "message": string;
    "resource"?: string;
    "line"?: number;
    "column"?: number;

    /** Creates a new ExtensionDiagnostic instance. */
    constructor($$source: Partial<ExtensionDiagnostic> = {}) {
        if (!("extensionId" in $$source)) {
            this["extensionId"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionDiagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionDiagnostic {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionDiagnostic($$parsedSource as Partial<ExtensionDiagnostic>);
    }
}

export class ExtensionInstance {
    "manifest": Manifest;
    "enabled": boolean;
    "active": boolean;
    "grants": string[];
    "settings": { [_ in string]?: any };
    "installDir": string;
    "installKind": InstallKind;
    "source": string;
    "packageHash"?: string;
    "installedAt": string;
    "error"?: string;
    "failureCount"?: number;
    "quarantined"?: boolean;

    /** Creates a new ExtensionInstance instance. */
    constructor($$source: Partial<ExtensionInstance> = {}) {
        if (!("manifest" in $$source)) {
            this["manifest"] = (new Manifest());
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("grants" in $$source)) {
            this["grants"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = {};
        }
        if (!("installDir" in $$source)) {
            this["installDir"] = "";
        }
        if (!("installKind" in $$source)) {
            this["installKind"] = InstallKind.$zero;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("installedAt" in $$source)) {
            this["installedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionInstance {
        const $$createField0_0 = $$createType14;
        const $$createField3_0 = $$createType15;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        if ("grants" in $$parsedSource) {
            $$parsedSource["grants"] = $$createField3_0($$parsedSource["grants"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField4_0($$parsedSource["settings"]);
        }
        return new ExtensionInstance($$parsedSource as Partial<ExtensionInstance>);
    }
}

export class ExtensionLog {
    "timestamp": string;
    "extensionId": string;
    "level": string;
    "message": string;
    "fields"?: { [_ in string]?: any };

    /** Creates a new ExtensionLog instance. */
    constructor($$source: Partial<ExtensionLog> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("extensionId" in $$source)) {
            this["extensionId"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionLog instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionLog {
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField4_0($$parsedSource["fields"]);
        }
        return new ExtensionLog($$parsedSource as Partial<ExtensionLog>);
    }
}

export class HostExecutionResult {
    "success": boolean;
    "data"?: any;
    "modified"?: boolean;
    "error"?: string;
    "timeMs": number;

    /** Creates a new HostExecutionResult instance. */
    constructor($$source: Partial<HostExecutionResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("timeMs" in $$source)) {
            this["timeMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostExecutionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HostExecutionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostExecutionResult($$parsedSource as Partial<HostExecutionResult>);
    }
}

export enum InstallKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InstallManaged = "managed",
    InstallDevelopment = "development",
};

export class KeybindingContribution {
    "command": string;
    "key": string;
    "when"?: string;

    /** Creates a new KeybindingContribution instance. */
    constructor($$source: Partial<KeybindingContribution> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeybindingContribution instance from a string or object.
     */
    static createFrom($$source: any = {}): KeybindingContribution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeybindingContribution($$parsedSource as Partial<KeybindingContribution>);
    }
}

/**
 * Manifest is the contract read without activating extension code.
 */
export class Manifest {
    "$schema"?: string;
    "manifestVersion": number;
    "id": string;
    "name": string;
    "version": string;
    "publisher": string;
    "description"?: string;
    "license"?: string;
    "homepage"?: string;
    "engines": Engines;
    "apiVersion": string;
    "main": string;
    "source"?: string;
    "activationEvents"?: string[];
    "permissions"?: string[];
    "contributes"?: Contributions;

    /** Creates a new Manifest instance. */
    constructor($$source: Partial<Manifest> = {}) {
        if (!("manifestVersion" in $$source)) {
            this["manifestVersion"] = 0;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("engines" in $$source)) {
            this["engines"] = (new Engines());
        }
        if (!("apiVersion" in $$source)) {
            this["apiVersion"] = "";
        }
        if (!("main" in $$source)) {
            this["main"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     */
    static createFrom($$source: any = {}): Manifest {
        const $$createField9_0 = $$createType17;
        const $$createField13_0 = $$createType15;
        const $$createField14_0 = $$createType15;
        const $$createField15_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("engines" in $$parsedSource) {
            $$parsedSource["engines"] = $$createField9_0($$parsedSource["engines"]);
        }
        if ("activationEvents" in $$parsedSource) {
            $$parsedSource["activationEvents"] = $$createField13_0($$parsedSource["activationEvents"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField14_0($$parsedSource["permissions"]);
        }
        if ("contributes" in $$parsedSource) {
            $$parsedSource["contributes"] = $$createField15_0($$parsedSource["contributes"]);
        }
        return new Manifest($$parsedSource as Partial<Manifest>);
    }
}

export class MenuContribution {
    "command": string;
    "when"?: string;
    "group"?: string;

    /** Creates a new MenuContribution instance. */
    constructor($$source: Partial<MenuContribution> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuContribution instance from a string or object.
     */
    static createFrom($$source: any = {}): MenuContribution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MenuContribution($$parsedSource as Partial<MenuContribution>);
    }
}

export class RuntimeStatus {
    "running": boolean;
    "protocolVersion": string;
    "activeCount": number;

    /** Creates a new RuntimeStatus instance. */
    constructor($$source: Partial<RuntimeStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("protocolVersion" in $$source)) {
            this["protocolVersion"] = "";
        }
        if (!("activeCount" in $$source)) {
            this["activeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus($$parsedSource as Partial<RuntimeStatus>);
    }
}

export class StatusBarContribution {
    "id": string;
    "text": string;
    "command"?: string;
    "priority"?: number;
    "when"?: string;

    /** Creates a new StatusBarContribution instance. */
    constructor($$source: Partial<StatusBarContribution> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusBarContribution instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusBarContribution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusBarContribution($$parsedSource as Partial<StatusBarContribution>);
    }
}

export class ViewContribution {
    "id": string;
    "container": string;
    "name": string;
    "renderer": string;
    "entry"?: string;
    "when"?: string;

    /** Creates a new ViewContribution instance. */
    constructor($$source: Partial<ViewContribution> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("renderer" in $$source)) {
            this["renderer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewContribution instance from a string or object.
     */
    static createFrom($$source: any = {}): ViewContribution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ViewContribution($$parsedSource as Partial<ViewContribution>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CommandContribution.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ViewContribution.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ConfigurationProperty.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = KeybindingContribution.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = MenuContribution.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $$createType10);
const $$createType12 = StatusBarContribution.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = Manifest.createFrom;
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = Engines.createFrom;
const $$createType18 = Contributions.createFrom;
