// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entity {
    "id": string;
    "kind": string;
    "label": string;
    "attrs": { [_ in string]?: string };
    "sources": Source[];
    "confidence": string;

    /** Creates a new Entity instance. */
    constructor($$source: Partial<Entity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("attrs" in $$source)) {
            this["attrs"] = {};
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entity instance from a string or object.
     */
    static createFrom($$source: any = {}): Entity {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attrs" in $$parsedSource) {
            $$parsedSource["attrs"] = $$createField3_0($$parsedSource["attrs"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField4_0($$parsedSource["sources"]);
        }
        return new Entity($$parsedSource as Partial<Entity>);
    }
}

export class Snapshot {
    "sessionId": string;
    "root": string;
    "version": number;
    "entities": Entity[];
    "warnings": string[];
    "scannedAt": string;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("entities" in $$source)) {
            this["entities"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField3_0($$parsedSource["entities"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Source {
    "detector": string;

    /**
     * root-relative, slash separated
     */
    "file": string;
    "line": number;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("detector" in $$source)) {
            this["detector"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Source.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Entity.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
